1. Write a Python Program to Add Two Matrices?
2. Write a Python Program to Multiply Two Matrices?
3. Write a Python Program to Transpose a Matrix?
4. Write a Python Program to Sort Words in Alphabetic Order?
5. Write a Python Program to Remove Punctuation From a String?

In [19]:
import numpy as np
a1= np.random.randint(low=0, high=8, size=(3, 2))
a2= np.random.randint(low=0, high=10, size=(3, 2))
a1,a2

(array([[0, 7],
        [0, 7],
        [1, 2]]),
 array([[2, 1],
        [4, 2],
        [4, 6]]))

In [20]:
#1

a1+a2

array([[2, 8],
       [4, 9],
       [5, 8]])

In [21]:
#2

a1*a2

array([[ 0,  7],
       [ 0, 14],
       [ 4, 12]])

In [63]:
#3
X= np.random.randint(low=0, high=8, size=(3, 2))

result = [[X[j][i] for j in range(len(X))] for i in range(len(X[0]))]

for r in result:
   print(r)

[5, 1, 2]
[0, 0, 2]


In [62]:
#4

a= 'ACFEBGHJSJDVCSHJKDJV'
c= []
d = ''
for i in a:
  c.append(i)
c.sort()
for j in c:
  d= d + j
d

'ABCCDDEFGHHJJJJKSSVV'

In [64]:
#5

s = "Hello, how are you ? Github. ;"
 
# printing original string
print("The original string is : " + s)
 
# initializing punctuations string
p = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
 
for i in s:
    if i in p:
        s = s.replace(i, "")
 
# result
print("The string after punctuation filter : " + s)

The original string is : Hello, how are you ? Github. ;
The string after punctuation filter : Hello how are you  Github 
